[package]
name = "rocket_tdd_json"
version = "0.1.0"
authors = ["dan <elastic7327@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket = "0.3.7"
rocket_codegen = "0.3.7"
